version: '2.2'

services:
    page:
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./:/usr/share/nginx/html
        restart: always